# Generated by Django 5.2.11 on 2026-06-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('telegram_chat_id', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
