# Generated by Django 6.0.6 on 2026-09-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_engineer_telegram_username_alter_engineer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='engineer',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='engineer',
            name='region',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Hudud / Viloyat'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='specialization',
            field=models.CharField(blank=True, default='ATM Servis Muhandisi', max_length=150, verbose_name='Mutaxassislik'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
