# Generated by Django 6.0.6 on 2026-07-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Hujjat nomi')),
                ('file', models.FileField(upload_to='uploaded_protocols/%Y/%m/', verbose_name='PDF fayl')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Active')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Protokol raqami')),
                ('protocol_date', models.DateField(db_index=True, verbose_name='Protokol sanasi')),
                ('performer_company', models.CharField(default='VTECH MCHJ', max_length=255, verbose_name='Ijrochi tashkilot')),
                ('customer_bank', models.CharField(default='TURON BANK ATB', max_length=255, verbose_name='Buyurtmachi bank')),
                ('document_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_data', to='maintenance.documentupload', verbose_name='Manba hujjat')),
            ],
            options={
                'verbose_name': 'Jadval',
                'verbose_name_plural': 'Jadvallar',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='№')),
                ('protocol_date', models.DateField(blank=True, null=True, verbose_name='Hujjat sanasi')),
                ('equipment_module', models.CharField(blank=True, default='', max_length=100, verbose_name='Модуль оборудования')),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Серийный номер')),
                ('filial_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование филиала')),
                ('mfo_bank', models.CharField(blank=True, default='', max_length=20, verbose_name='МФО банка')),
                ('part_name', models.TextField(db_index=True, verbose_name='Наименование запчастей')),
                ('measurement_unit', models.CharField(default='услуга (сум)', max_length=50, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Кол-во')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Цена (СУМ)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма (СУМ)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='QQS (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма НДС')),
                ('total_with_vat', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Стоимость с учетом НДС')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.documentupload', verbose_name='Hujjat')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.maintenanceprotocol', verbose_name='Protokol')),
            ],
            options={
                'verbose_name': "Umumiy ma'lumot",
                'verbose_name_plural': "Umumiy ma'lumotlar",
                'ordering': ['row_number'],
            },
        ),
    ]
