"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.11.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from celery.schedules import crontab
from decouple import config
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k(v*f1qm$22!l8#+8qpjmq&@clwphmn*dc!t+tie@xiqco6+fp'
TELEGRAM_BOT_TOKEN  = "8920660555:AAG47cziMaxMINz9jWEnP7FnIgk3MnbGx3o"
GROUP_CHAT_ID = -1002229184837
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = [
    # "atm-info.turonbank.uz",
    # "172.16.100.49",
    # "127.0.0.1",
    # "172.17.104.41",  # backend kompyuter
    # "172.17.104.50",  # boshqa kompyuter
    # "localhost",
    # ".ngrok-free.app",
    # "flashily-coastal-feel.ngrok-free.dev",
    "*"
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]
CSRF_TRUSTED_ORIGINS = [
    "https://atm-info.turonbank.uz",
    "http://atm-info.turonbank.uz",
    "https://flashily-coastal-feel.ngrok-free.dev",
    "http://localhost:3000",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.atms',
    'apps.users',
    'apps.notifications',
    'apps.monitoring',
    'apps.common',
    'apps.Bankomat_hisobot',
    'apps.maintenance',
    "apps.ai_analytics",
    "django_filters",
    "rest_framework",
    "drf_spectacular",
    "corsheaders"

]
CORS_ALLOW_ALL_ORIGINS = True
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_URLCONF = 'config.urls'
from dotenv import load_dotenv
import os

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         "DIRS": [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
REST_FRAMEWORK = {

    "DEFAULT_SCHEMA_CLASS": (
        "drf_spectacular.openapi.AutoSchema"
    ),

    "DEFAULT_FILTER_BACKENDS": [

        "django_filters.rest_framework.DjangoFilterBackend",

        "rest_framework.filters.SearchFilter",

        "rest_framework.filters.OrderingFilter",

    ],

}
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_SOFT_TIME_LIMIT = 60
CELERY_TASK_TIME_LIMIT = 120
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tashkent'
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {

    # 1. ATM larni olish
    "sync-atms-morning": {
        "task": "apps.atms.tasks.sync_atms",
        "schedule": crontab(hour=9, minute=15),
    },

    "sync-atms-evening": {
        "task": "apps.atms.tasks.sync_atms",
        "schedule": crontab(hour=15, minute=5),
    },

    # 2. Notification yaratish
    "generate-notifications-morning": {
        "task": "apps.notifications.tasks.generate_notifications",
        "schedule": crontab(hour=9, minute=20),
    },

    "generate-notifications-evening": {
        "task": "apps.notifications.tasks.generate_notifications",
        "schedule": crontab(hour=15, minute=8),
    },

    # 3. Telegramga yuborish


    "send-notifications": {
    "task": "apps.notifications.tasks.send_notifications",
    "schedule": crontab(minute="*"),
},
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
MEDIA_URL = '/media/'
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Tashkent'
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SPECTACULAR_SETTINGS = {

    "TITLE": "ATM Monitoring API",

    "DESCRIPTION": (
        "ATM monitoring, business analytics, "
        "maintenance and dashboard API"
    ),

    "VERSION": "1.0.0",

    "SERVE_INCLUDE_SCHEMA": False,

    "TAGS": [

        {
            "name": "ATM",
            "description": (
                "ATM list, search, filters "
                "and detail endpoints"
            ),
        },

        {
            "name": "Dashboard",
            "description": (
                "ATM analytics and business dashboard"
            ),
        },

        {
            "name": "Maintenance",
            "description": (
                "Technical maintenance operations"
            ),
        },

    ],

}
