# Generated by Django 6.0.6 on 2026-07-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_engineer_telegram_username_alter_engineer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(unique=True)),
                ('atm_uid', models.CharField(max_length=255, null=True)),
                ('serial', models.CharField(db_index=True, max_length=100)),
                ('tid', models.CharField(db_index=True, max_length=100)),
                ('extra_attrs', models.JSONField(blank=True, null=True)),
                ('branch_number', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('responsible_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.engineer')),
            ],
        ),
        migrations.CreateModel(
            name='ATMCurrentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_status', models.CharField(max_length=50)),
                ('service_status', models.CharField(max_length=50)),
                ('app_status', models.CharField(max_length=50)),
                ('app_conn_status', models.CharField(max_length=50)),
                ('cash_amount', models.BigIntegerField(default=0)),
                ('last_online', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atms.atm')),
            ],
        ),
        migrations.CreateModel(
            name='ATMEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BANKOMATDA_PUL_KAM', 'Cash low'), ("TRANZAKSIYA_YO'Q", 'No transaction'), ('BANKOMAT_OFFLINE', 'Offline'), ('BANKOMAT_ONLINE', 'Online')], max_length=50)),
                ('message', models.TextField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='atms.atm')),
            ],
        ),
    ]
