# Generated by Django 6.0.6 on 2026-06-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(unique=True)),
                ('atm_uid', models.CharField(max_length=255, null=True)),
                ('serial', models.CharField(max_length=100)),
                ('tid', models.CharField(max_length=100)),
                ('branch_number', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('model_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATMCurrentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_status', models.CharField(max_length=50)),
                ('service_status', models.CharField(max_length=50)),
                ('app_status', models.CharField(max_length=50)),
                ('app_conn_status', models.CharField(max_length=50)),
                ('cash_amount', models.BigIntegerField(default=0)),
                ('last_online', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='atms.atm')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atms.atm')),
            ],
        ),
    ]
