# Generated by Django 6.0.6 on 2026-06-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atms.atm')),
            ],
        ),
    ]
