# Generated by Django 6.0.6 on 2026-09-08 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0001_initial'),
        ('users', '0003_engineer_avatar_url_engineer_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTechATMSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btech_id', models.BigIntegerField(db_index=True, unique=True)),
                ('serial', models.CharField(db_index=True, max_length=100)),
                ('tid', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(default='production', max_length=50)),
                ('service_status', models.CharField(default='InService', max_length=50)),
                ('app_conn_status', models.CharField(default='Online', max_length=50)),
                ('agent_status', models.CharField(default='online', max_length=50)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('total_cash_uzs', models.BigIntegerField(default=0)),
                ('total_cash_usd', models.BigIntegerField(default=0)),
                ('address', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('branch_number', models.CharField(blank=True, default='', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'BTech ATM Snapshot',
                'verbose_name_plural': 'BTech ATM Snapshots',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BTechConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer_token', models.TextField(default='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM2NiwiaWF0IjoxNzg4ODM5NzA3LCJleHAiOjE3ODkwOTg5MDcsImp0aSI6IjNiY2JhMmNhLWFkMTktNDUyOC1iN2YxLTg1OTEwMTIwNmMwMCJ9.2YiXTsWyveVXdIhY2SrhcJrXvtq3UfmaAV8NfU2_qQg', help_text="Har 3 kunda yangilanadigan BTech JWT Bearer Token (Bearer so'zi bilan yoki uningsiz kiriting)", verbose_name='BTech Bearer Token')),
                ('api_url', models.CharField(default='https://monitoring.btech.uz/api/base/atm/?clientId=&vendorId=&modelId=&functionId=&variantId=&atmGroupId=&countryId=&regionId=&cityId=&hashTags=&appConnectionStatus=all&agentConnectionStatus=online&hwFaults=&atmStatus=production&withUnitsTurnoverTotal=true&offset=0&limit=500&lang=en', max_length=500, verbose_name='BTech API URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi sinxronizatsiya vaqti')),
                ('last_sync_status', models.CharField(default='NOT_SYNCED', max_length=150, verbose_name='Oxirgi sinxronizatsiya holati')),
            ],
            options={
                'verbose_name': 'BTech Token Config',
                'verbose_name_plural': 'BTech Token Configs',
            },
        ),
        migrations.AlterField(
            model_name='atm',
            name='responsible_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_atms', to='users.engineer'),
        ),
    ]
