# Generated by Django 5.2.11 on 2026-06-19 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0002_atmevent'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='responsible_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.engineer'),
        ),
    ]
