# Generated by Django 5.2.11 on 2026-06-19 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0003_atm_responsible_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='extra_attrs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='atm',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ATMCardCassette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('unit_id', models.CharField(max_length=50, null=True)),
                ('ctype', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('values', models.IntegerField(default=0)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atms.atm')),
            ],
        ),
    ]
