# Generated by Django 5.2.11 on 2026-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0004_atm_extra_attrs_alter_atm_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='atm',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='atmevent',
            name='is_active',
        ),
        migrations.AddField(
            model_name='atmevent',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atm',
            name='serial',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='atm',
            name='tid',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='atmevent',
            name='event_type',
            field=models.CharField(choices=[('OFFLINE', 'OFFLINE'), ('ONLINE', 'ONLINE'), ('CASH_LOW', 'CASH_LOW'), ('CASSETTE_EMPTY', 'CASSETTE_EMPTY'), ('NO_TRANSACTION', 'NO_TRANSACTION')], max_length=50),
        ),
    ]
