# Generated by Django 6.0.6 on 2026-06-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0005_remove_atm_created_at_remove_atm_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitoringSnapshot',
        ),
    ]
