# Generated by Django 5.2.11 on 2026-06-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0006_delete_monitoringsnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmevent',
            name='payload',
        ),
        migrations.AlterField(
            model_name='atmevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='atmevent',
            name='event_type',
            field=models.CharField(db_index=True, default='SMART_ALERT', max_length=50),
        ),
        migrations.AlterField(
            model_name='atmevent',
            name='is_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
