# Generated by Django 5.2.11 on 2026-06-23 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0007_remove_atmevent_payload_alter_atmevent_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmevent',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atmevent',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='atmevent',
            name='atm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='atms.atm'),
        ),
        migrations.AlterField(
            model_name='atmevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atmevent',
            name='event_type',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('CASH_LOW', 'Cash Low'), ('CASSETTE_EMPTY', 'Cassette Empty'), ('SMART_ALERT', 'Smart Alert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='atmevent',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
