# Generated by Django 5.2.11 on 2026-06-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0008_atmevent_meta_atmevent_status_alter_atmevent_atm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmevent',
            name='event_type',
            field=models.CharField(choices=[('CASH_LOW', 'Cash low'), ('NO_TRANSACTION', 'No transaction'), ('OFFLINE', 'Offline'), ('ONLINE', 'Online')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ATMCardCassette',
        ),
    ]
