# Generated by Django 5.2.11 on 2026-06-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0009_alter_atmevent_event_type_delete_atmcardcassette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmevent',
            name='event_type',
            field=models.CharField(choices=[('BANKOMATDA_PUL_KAM_QOLGAN', 'Cash low'), ("BANKOMATDA_TRANZAKSIYA_YO'Q", 'No transaction'), ('BANKOMAT_OFFLINE', 'Offline'), ('BANKOMAT_ONLINE', 'Online')], max_length=50),
        ),
    ]
