# Generated by Django 5.2.11 on 2026-06-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0010_alter_atmevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmevent',
            name='event_type',
            field=models.CharField(choices=[('BANKOMATDA_PUL_KAM', 'Cash low'), ("TRANZAKSIYA_YO'Q", 'No transaction'), ('BANKOMAT_OFFLINE', 'Offline'), ('BANKOMAT_ONLINE', 'Online')], max_length=50),
        ),
    ]
