# Generated by Django 6.0.6 on 2026-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='notification',
            name='chat_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
