# Generated by Django 5.2.11 on 2026-06-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atms', '0010_alter_atmevent_event_type'),
        ('notifications', '0002_rename_message_notification_text_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('event', 'chat_id')},
        ),
    ]
