# Generated by Django 6.0.6 on 2026-07-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='atm/imports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('result', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATMTURON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('name', models.CharField(max_length=255, verbose_name='ATM nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('terminal_id', models.CharField(db_index=True, max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('UZCARD', 'Uzcard'), ('HUMO', 'Humo')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['region', 'terminal_id'],
            },
        ),
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='atm/imports/')),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATMTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('VASH', 'Vash')], db_index=True, max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('SOZ', 'Soz'), ('NOSOZ', 'Nosoz')], db_index=True, max_length=20)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('inventory_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('terminal_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('account_23510', models.CharField(blank=True, max_length=100)),
                ('account_45265', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical', to='Bankomat_hisobot.atmturon')),
            ],
            options={
                'verbose_name': 'ATM Technical',
                'verbose_name_plural': 'ATM Technicals',
                'ordering': ('terminal_id',),
            },
        ),
        migrations.CreateModel(
            name='ATMMonthlyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('expense', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('income', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statistics', to='Bankomat_hisobot.atmturon')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('atm', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ATMYearStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('card_type', models.CharField(choices=[('UZCARD', 'Uzcard'), ('HUMO', 'Humo')], db_index=True, max_length=20)),
                ('expense', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('income', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_statistics', to='Bankomat_hisobot.atmturon')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('atm', 'year', 'card_type')},
            },
        ),
    ]
