# Generated by Django 6.0.6 on 2026-06-26 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ATMType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_address', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Soz'), ('inactive', 'Nosoz')], default='active', max_length=20)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('inventory_number', models.CharField(max_length=100, unique=True)),
                ('merchant_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('terminal_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('atm_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bankomat_hisobot.atmmodel')),
                ('atm_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bankomat_hisobot.atmtype')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atms', to='Bankomat_hisobot.branch')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='Bankomat_hisobot.region'),
        ),
        migrations.CreateModel(
            name='ATMStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField()),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='Bankomat_hisobot.atm')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('atm', 'period')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('region', 'name')},
        ),
    ]
