# Generated by Django 6.0.6 on 2026-07-22 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankomat_hisobot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_monthly', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATMServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bxm_name', models.CharField(blank=True, max_length=255)),
                ('mfo', models.CharField(blank=True, db_index=True, max_length=20)),
                ('merchant_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('card_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('btech_monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('glob_monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_contract', to='Bankomat_hisobot.atmturon')),
            ],
            options={
                'ordering': ('atm__terminal_id',),
            },
        ),
        migrations.CreateModel(
            name='ATMServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('payment_type', models.CharField(choices=[('INCASSATION', 'Incassation'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Bankomat_hisobot.atmservicecontract')),
            ],
            options={
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.AddIndex(
            model_name='atmservicecontract',
            index=models.Index(fields=['merchant_id'], name='Bankomat_hi_merchan_6dcd9a_idx'),
        ),
        migrations.AddIndex(
            model_name='atmservicecontract',
            index=models.Index(fields=['mfo'], name='Bankomat_hi_mfo_fedc85_idx'),
        ),
        migrations.AddIndex(
            model_name='atmservicepayment',
            index=models.Index(fields=['year', 'month'], name='Bankomat_hi_year_39efc8_idx'),
        ),
        migrations.AddIndex(
            model_name='atmservicepayment',
            index=models.Index(fields=['payment_type'], name='Bankomat_hi_payment_0a743c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='atmservicepayment',
            unique_together={('contract', 'year', 'month', 'payment_type')},
        ),
    ]
