# Generated by Django 6.0.6 on 2026-07-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankomat_hisobot', '0002_atmservicetype_atmservicecontract_atmservicepayment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ATMServiceType',
        ),
        migrations.AddField(
            model_name='atmservicecontract',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='Contract start date'),
        ),
    ]
