# Generated by Django 6.0.6 on 2026-07-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankomat_hisobot', '0003_delete_atmservicetype_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='atmservicecontract',
            name='Bankomat_hi_merchan_6dcd9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='atmservicecontract',
            name='Bankomat_hi_mfo_fedc85_idx',
        ),
        migrations.RemoveField(
            model_name='atmservicecontract',
            name='bxm_name',
        ),
        migrations.RemoveField(
            model_name='atmservicecontract',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='atmservicecontract',
            name='contract_start',
        ),
        migrations.RemoveField(
            model_name='atmservicecontract',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='atmservicecontract',
            name='mfo',
        ),
    ]
