# Generated by Django 6.0.6 on 2026-07-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankomat_hisobot', '0004_remove_atmservicecontract_bankomat_hi_merchan_6dcd9a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmtechnical',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sotib olingan sana'),
        ),
        migrations.AddField(
            model_name='atmtechnical',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Sotib olingan qiymati'),
        ),
    ]
